development:
    url: yoursite.url
    database:
        type: mysql # mysql, postgresql, sqlite
        host: localhost
        port: 3306
        database: database_name
        username: root
        password: password
        charset: utf8
    email: Your Name <your@email.com> # FROM address for system emails
    mailgun:
        key: your_api_key
        domain: your_domain

production:
    url: yoursite.url
    database:
        type: mysql # mysql, postgresql, sqlite
        host: localhost
        port: 3306
        database: database_name
        username: root
        password: password
        charset: utf8
    email: Your Name <your@email.com> # FROM address for system emails
    mailgun:
        key: your_api_key
        domain: your_domain
